name: Metrics Age

on:
  schedule:
    - cron: "0 0 1 1 *"  # Every January 1st at midnight
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-age:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Calculate current age
        id: calculate_age
        run: |
          BIRTH_YEAR=2001
          CURRENT_YEAR=$(date +%Y)
          AGE=$((CURRENT_YEAR - BIRTH_YEAR - 1))

          echo "CURRENT_AGE=$AGE" >> $GITHUB_ENV

          # Debug output
          echo "Birth year: $BIRTH_YEAR | Current year: $CURRENT_YEAR | Calculated age: $AGE"

      - name: Update age in README
        run: |
          sed -i "s/<AGE>/${{ env.CURRENT_AGE }}/g" README.md
          sed -i "s/[0-9]\+-year-old/${{ env.CURRENT_AGE }}-year-old/g" README.md

      - name: Commit and push changes
        env:
          GIT_TOKEN: ${{ secrets.METRICS_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: run metrics-age [skip ci]" || echo "No changes to commit"
          git push
